SocialGouv/1000jours

back/docker-compose.yaml, back/hasura/metadata/tables.yaml
https://hasura.io/docs/latest/graphql/core/auth/authentication/unauthenticated-access.html#unauthenticated-access
https://hasura.io/docs/latest/graphql/core/auth/authorization/common-roles-auth-examples.html#anonymous-users-example
=> fix(api): permet aux clients non-authentifiés de faire des requêtes

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/strapi.ts
fix yet another issue with azure volumes
=> fix(k8s): force recreate strapi deployment

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/strapi.ts, back/strapi/Dockerfile
ensure deployment is always on the same node
=> fix(strapi): nodeSelector

front/components/HeaderApp.tsx, front/screens/Onboarding.tsx, front/screens/Profile.tsx
=> fix: 🐛 Corrige les retours UI (Onboarding et Profil)

back/strapi/api-src/article/models/article.settings.ts, back/strapi/extensions/ckeditor5/admin/src/config/ckeditor.js
Et configuration de l'éditeur WYSIWYG :
- suppression du bouton de header.
=> feat(articles): ajout des titres de paragraphes

front/components/article/DidYouKnow.tsx, front/components/article/InShort.tsx, front/components/article/SubTitle.tsx, front/components/article/TextHtml.tsx, front/screens/ArticleDetail.tsx, front/types.tsx
=> feat: 🎸 Ajoute texteTitre1 et texteTitre2 (article)

front/components/article/Thematics.tsx, front/components/timeline/TimlineStep.tsx, front/navigation/index.tsx
Ajoute une marge sur les sous titres d'article et remplace les
"onTouchEnd"
✅ Closes: #133
=> fix: 🐛 Ajoute une marge pour afficher les sous titres d'article

front/components/article/DidYouKnow.tsx, front/components/article/InShort.tsx, front/components/article/Links.tsx, front/components/article/SubTitle.tsx, front/components/article/TextHtml.tsx, front/components/article/Thematics.tsx, front/components/article/Title.tsx, front/constants/Labels.ts, front/screens/ArticleDetail.tsx
=> fix: 🐛 Corrige les problèmes de font (Article) et lien invalide

front/components/form/InputDate.tsx, front/screens/Profile.tsx
=> fix: 🐛 Corrige la saisie de date compliqué sous iOS

front/components/timeline/TimlineStep.tsx
=> fix: 🐛 Corrige la position du numéro de l'étape (Timeline)

front/screens/ListArticles.tsx
=> feat: 🎸 je consulte les articles liés à une étape

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/strapi.ts
=> build(k8s): add BACKOFFICE_URL env variable

back/docker-compose.yaml, back/strapi/api/article/controllers/article.js, back/strapi/api/article/models/article.settings.js, back/strapi/api/article/services/index.js, back/strapi/config/server.js, front/components/article/ImageBanner.tsx, front/screens/ListArticles.tsx
=> fix(article): complète les urls en liens absolus

front/components/calendar/agenda.tsx, front/constants/Labels.ts, front/screens/Profile.tsx, front/screens/TabCalendarScreen.tsx, front/storage/storage-keys.ts, front/types.tsx
=> feat: 🎸 Affiche les événements en fonction de la date saisie

.vscode/settings.json, front/components/calendar/agenda.tsx, front/components/form/DatePicker.tsx, front/components/index.ts, front/constants/Labels.ts, front/constants/formats.ts, front/constants/index.ts, front/constants/localizations.ts, front/constants/platform.constants.ts, front/constants/shadow.constants.ts, front/screens/Profile.tsx
=> feat: 🎸 Ajoute la nouvelle version du datePicker

front/App.tsx, front/constants/Labels.ts, front/constants/storageKeys.constants.ts, front/screens/epdsSurvey/epdsLoadPreviousSurvey.component.tsx, front/screens/epdsSurvey/epdsResult.component.tsx, front/screens/epdsSurvey/epdsSurveyContent.component.tsx, front/screens/epdsSurvey/epdsSurveyFooter.component.tsx, front/screens/epdsSurvey/epdsSurveyQuestionsList.component.tsx, front/screens/index.ts, front/utils/epdsSurvey.util.ts, front/utils/storage.util.ts
US #182 
Cas de test : 
- lancer le questionnaire EPDS
- répondre à 2-3 questions
- revenir sur l'Accueil (ou n'importe quel autre écran)
- relancer le questionnaire
- vous devez avoir un message demandant à continuer le précédent questionnaire ou à en recommencer un nouveau
- si vous continuez, vous revenez sur la dernière question posée
- si vous recommencer, vous repartez de 0
=> Conserver contexte questionnaire

front/components/calendar/events.tsx, front/constants/Labels.ts, front/screens/TabCalendarScreen.tsx
Version draft, en attendant d'avoir les maquettes du calendrier.
=> feat: 🎸 Permet d'afficher les événements sous forme de liste

front/components/form/Checkbox.tsx, front/constants/Labels.ts, front/constants/spacings.ts, front/screens/epdsSurvey/epdsGenderEntry.component.tsx, front/screens/epdsSurvey/epdsQuestion.component.tsx, front/screens/epdsSurvey/epdsSurveyContent.component.tsx, front/screens/epdsSurvey/epdsSurveyFooter.component.tsx, front/screens/epdsSurvey/epdsSurveyQuestionsList.component.tsx, front/screens/epdsSurvey/epdsSurveyQuestionsPagination.component.tsx, front/screens/epdsSurvey/epdsSurveyScreen.component.tsx, front/type/epdsSurvey.types.ts, front/utils/epdsSurvey.util.ts
Le document de Perrine sur ses retours : https://nextcloud.fabrique.social.gouv.fr/apps/onlyoffice/62098?filePath=%2F1000j%2FBrique%203%20premiers%20mois%2FDesign%2FReview%20Design%2FDesign%20Review.docx
=> Design review questionnaire

back/strapi/api/reponses-epds/models/reponses-epds.settings.json, front/constants/Labels.ts, front/constants/epdsConstants.constants.ts, front/screens/epdsSurvey/epdsGenderEntry.component.tsx, front/screens/epdsSurvey/epdsQuestion.component.tsx, front/screens/epdsSurvey/epdsSurveyFooter.component.tsx, front/screens/epdsSurvey/epdsSurveyQuestionsList.component.tsx, front/screens/epdsSurvey/epdsSurveyQuestionsPagination.component.tsx, front/type/epdsSurvey.types.ts
Retours de démo:
- un petit warning quand on arrive sur la première question du questionnaire, comme quoi chaque élément dans la liste dans le fichier epdsSurveyQuestionsPagination.component.tsx doit avoir un index, donc je l'ai mis et j'ai fait une petit refacto
- ajouter le genre "Non-binaire" dans l'écran demandant le genre, donc j'ai fait la modif côté front et back (côté back, l'enum n'accepte pas les caractères spéciaux, d'où le "Nonbinaire" attaché)
=> Retours demo

.gitlab-ci.yml, .k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/package.json, .k8s/yarn.lock
get rid of legacy gitlab docker registry
=> fix(ci): upgrade deps

front/components/article/TextHtml.tsx, front/constants/platform.constants.ts, front/package.json, front/screens/ArticleDetail.tsx, front/yarn.lock
=> fix: 🐛 Corrige l'affichage des vidéos dans la fiche article

front/constants/aroundMe.constants.ts, front/screens/aroundMe/tabAroundMeScreen.component.tsx, front/utils/epdsSurvey.util.ts
Closes #272 
J'en ai profité pour bloquer le dézoom de la carto à un certain niveau (pour ne pas se retrouver avec trop d'adresses remontées)
=> fix(epds): fix décoche case questionnaire

front/components/article/Links.tsx, front/constants/Labels.ts
=> feat: 🎸 Ajoute un titre au dessus des liens (article)

front/navigation/BottomTabNavigator.tsx
=> fix(epds): fix bouton Accueil

front/constants/Labels.ts, front/screens/epdsSurvey/epdsResultInformation/epdsResultContactParagraph.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultInformation.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultSimpleParagraph.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultUrlParagraph.component.tsx, front/screens/epdsSurvey/epdsSurveyContent.component.tsx, front/screens/epdsSurvey/epdsSurveyFooter.component.tsx, front/screens/epdsSurvey/epdsSurveyScreen.component.tsx
=> fix(epds): design + tech review

back/strapi/api/cartographie-poi/config/schema.graphql.js, back/strapi/api/cartographie-poi/controllers/cartographie-poi.js, back/strapi/api/cartographie-poi/services/index.js, back/strapi/api/cartographie-types/models/cartographie-types.settings.json
=> feat(carto): Ajoute les paramètres de recherche de POI par types et thématiques

front/assets/html/cgu.html
=> fix: 🐛 Corrige le document des cgu

front/App.tsx, front/components/base/notification.component.tsx, front/constants/Colors.ts, front/constants/Labels.ts, front/constants/storageKeys.constants.ts, front/navigation/index.tsx, front/screens/TabHomeScreen.tsx, front/types.tsx, front/utils/notification.util.ts, front/yarn.lock
=> feat: 🎸 Ajoute les notifications changement d'étapes

back/strapi/api/cartographie-poi/config/schema.graphql.js, back/strapi/api/cartographie-poi/controllers/cartographie-poi.js, back/strapi/api/cartographie-poi/services/index.js
https://github.com/SocialGouv/1000jours/issues/375
=> feat(carto): Ajoute le filtre de POIs par étapes dans l'API

README.md, front/assets/html/cgu.html, front/constants/Labels.ts, front/fastlane/Preview.html, front/fastlane/metadata/fr-FR/name.txt
=> fix: 🐛 Modifie certains textes (Nos 1000 jours + calendrier)

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/package.json, .k8s/yarn.lock
=> chore(deps): @socialgouv/kosko-charts update 6.4.1

back/strapi/config/plugins.js, back/strapi/package.json, back/strapi/yarn.lock
Ajoute sentry au backoffice
✅ Closes: #23
=> chore: 🤖 sentry

.k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/environments/prod/strapi.configmap.yaml, back/strapi/config/plugins.js, back/strapi/package.json, back/strapi/yarn.lock
=> feat(k8s): add SENTRY_DSN url

front/constants/Labels.ts, front/screens/aroundMe/aroundMeFilter.component.tsx, front/screens/aroundMe/tabAroundMeScreen.component.tsx, front/screens/epdsSurvey/epdsResult.component.tsx, front/screens/epdsSurvey/epdsSurveyScreen.component.tsx, front/utils/linking.util.ts, front/utils/tracker.util.ts
Closes #427 
Closes #429 
Closes #430 
Closes #354 
+ ajout de Matomo dans la carto (tabAroundMeScreen.component.tsx) et l'EPDS (epdssurveyscreen.component.tsx)
=> fix(epds): modification des textes du questionnaire

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/cache/index.ts, .k8s/package.json, .k8s/yarn.lock
=> chore(deps): @socialgouv/kosko-charts update 6.5.0

front/screens/Profile.tsx
=> feat: 🎸 Corrige le profil (checkbox non sauvegardé)

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/cache/index.ts, .k8s/components/strapi.ts
=> fix(k8s): add hpa in preprod and prod env

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/cache/nginx.conf
=> fix(k8s): change nginx cache folder

.k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/cache/index.ts
=> fix(k8s): remove pvc on strapi-cache

front/screens/aroundMe/searchByPostalCode.component.tsx
=> fix(carto): loader caché si CP invalide

back/strapi/package.json
cf. https://strapi.io/documentation/developer-docs/latest/getting-started/usage-information.html#commitment-to-our-users-data-collection
=> fix(strapi): Désactive le tracking de données

front/constants/platform.constants.ts, front/screens/aroundMe/addressDetails.component.tsx, front/screens/aroundMe/slidingUpPanelAddressesList.component.tsx, front/screens/aroundMe/tabAroundMeScreen.component.tsx
=> feat(carto): affichage cartouche et volet

front/screens/Profile.tsx, front/screens/TabHomeScreen.tsx
=> fix: 🐛 Corrige la mise à jour du profil

front/screens/aroundMe/tabAroundMeScreen.component.tsx
=> fix(carto): cacher le volet lorsqu'aucune adresse n'a été trouvée

back/strapi/api/article/models/article.settings.js, front/screens/listArticles.component.tsx
=> feat(articles): Ajoute l'ordre aux articles pour les trier

front/components/base/errorMessage.component.tsx, front/constants/storageKeys.constants.ts, front/screens/Profile.tsx, front/screens/TabHomeScreen.tsx, front/utils/notification.util.ts, front/utils/step.util.ts, front/utils/storage.util.ts
=> fix: 🐛 Corrige le calcul de l'étape courante

front/screens/Profile.tsx, front/utils/tracker.util.ts
=> feat: 🎸 Ajoute le choix du profil dans Matomo

front/screens/Profile.tsx
=> fix: 🐛 Corrige le trackerEvent Matomo sur le profil

front/constants/Labels.ts, front/screens/TabCalendarScreen.tsx
=> feat: 🎸 Ajoute un bouton pour maj son profil (calendrier)

front/components/aroundMe/fetchPoisCoords.component.tsx, front/constants/aroundMe.constants.ts, front/constants/databaseQueries.constants.ts, front/type/aroundMe.types.ts, front/type/index.ts
=> feat(carto): annulation du filtre si moins de 20 POI avec le filtre

front/screens/aroundMe/slidingUpPanelAddressesList.component.tsx
=> feat(carto): diminution du volet lorsqu'on est en haut du scroll

back/strapi/api/reponses-epds/config/routes.json, back/strapi/api/reponses-epds/config/schema.graphql.js, back/strapi/api/reponses-epds/controllers/reponses-epds.js, back/strapi/api/reponses-epds/services/index.js, back/strapi/config/plugins.js, back/strapi/package.json, back/strapi/yarn.lock
refs #511
Variables d'environnement à configurer :
- `MAIL_HOST`
- `MAIL_PORT`
- `MAIL_USER`
- `MAIL_PASSWORD`
- `MAIL_SEND_FROM` (contact)
- `MAIL_SEND_TO` (mama blues)
=> feat(epds): Envoie un email si le parent souhaite être contacté suite au test

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/environments/dev/azure-volume.sealed-secret.yaml, .k8s/environments/dev/strapi.sealed-secret.yaml
=> test(k8s): Supprime les liens symbolique de test

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/package.json, .k8s/yarn.lock
=> chore(k8s): update @socialgouv/kosko-charts to 8.0.2

front/components/base/errorMessage.component.tsx, front/components/base/notification.component.tsx, front/components/calendar/events.component.tsx, front/constants/Labels.ts, front/constants/storageKeys.constants.ts, front/screens/TabCalendarScreen.tsx, front/screens/TabHomeScreen.tsx, front/utils/logging.util.ts, front/utils/notification.util.ts
=> feat: 🎸 Ajoute les notifications des événements

front/App.tsx, front/components/base/notification.component.tsx, front/constants/Labels.ts, front/constants/storageKeys.constants.ts, front/screens/Profile.tsx, front/utils/tracker.util.ts
=> feat: 🎸 Ajoute des stats dans Matomo

front/components/aroundMe/fetchPoisCoords.component.tsx, front/screens/aroundMe/searchByPostalCode.component.tsx, front/screens/aroundMe/tabAroundMeScreen.component.tsx
=> fix: 🐛 Corrige le loader sur la carto (access GPS : refused)

front/screens/aroundMe/aroundMeFilter.component.tsx, front/screens/listArticles.component.tsx, front/utils/tracker.util.ts
=> feat: 🎸 Ajoutes les stats des filtres dans Matomo

front/App.tsx
=> fix: 🐛 Corrige l'envoie de la stat "Ouverture de l'app"

.github/workflows/expo-build-prod.yml, .github/workflows/expo-publish-preprod.yml
=> feat: 🎸 Ajoute Matomo pour la PREPROD (APP_ID : 46)

front/components/base/checkbox.component.tsx, front/components/base/headerApp.component.tsx, front/components/base/notification.component.tsx, front/navigation/index.tsx, front/screens/aroundMe/aroundMeFilter.component.tsx, front/screens/epdsSurvey/epdsQuestion.component.tsx, front/screens/listArticles.component.tsx
iOS Guideline 4.0 - Design (App refused)
✅ Closes: #560
=> fix: 🐛 Améliore l'UX/UI (buttons, checkbox)

front/constants/platform.constants.ts, front/constants/spacings.ts, front/screens/epdsSurvey/epdsLightResult.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultContactParagraph.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultInformation.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultSimpleParagraph.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultUrlParagraph.component.tsx
=> fix: 🐛 Corrige les problèmes d'affichage sur tablette

front/App.tsx
=> fix: 🐛 Corrige l'initialisation de Matomo

front/constants/Labels.ts
=> fix(labels): correction erreurs texte

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap
=> fix: snaps

.github/workflows/expo-build-prod.yml, .github/workflows/expo-publish-develop.yml, front/package.json
Ajoute un nouvel env "develop" et supprime les secrets inutiles
=> chore: 🤖 Ajoute un nouvel env "develop"

front/components/base/tags.component.tsx, front/components/calendar/events.component.tsx, front/components/index.ts, front/screens/TabCalendarScreen.tsx, front/types.tsx
=> feat: 🎸 Ajoute les tags (thematique, etapes) sur les events

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/jobs-restore.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/pg.ts, .k8s/package.json, .k8s/yarn.lock
=> build(k8s): update to @socialgouv/kosko-charts 9.2

back/strapi/api/reponses-epds/models/reponses-epds.settings.json
=> feat(result): Add source for epds result

front/screens/aroundMe/customMapMarker.component.tsx, front/screens/aroundMe/tabAroundMeScreen.component.tsx
=> fix(carto): fix lenteur carto

front/assets/html/accessibilite.html, front/components/menu/accessibility.component.tsx, front/components/menu/menu.component.tsx, front/constants/Labels.ts
=> feat: 🎸 Ajoute la page "accessibilité"

front/screens/aroundMe/customMapMarker.component.tsx, front/screens/aroundMe/tabAroundMeScreen.component.tsx
=> fix(carto): fix loader

front/screens/aroundMe/searchByPostalCode.component.tsx
=> fix(carto): add accuracy param

front/screens/epdsSurvey/beContacted.component.tsx, front/screens/epdsSurvey/epdsResultInformation/epdsResultContactParagraph.component.tsx
=> fix(epds): correction des noms des contacts + agrandissement zone cliquable de la modale

front/screens/TabCalendarScreen.tsx
=> fix: 🐛 Corrige la synchro des events sur Android

back/strapi/api/cartographie-poi/config/routes.json, back/strapi/api/cartographie-poi/config/schema.graphql.js, back/strapi/api/cartographie-poi/controllers/cartographie-poi.js, back/strapi/api/cartographie-poi/services/index.js, front/constants/databaseQueries.constants.ts
=> fix(carto): ajout de la route pour les suggestions

front/constants/Labels.ts, front/constants/aroundMe.constants.ts, front/screens/aroundMe/searchByPostalCode.component.tsx
=> fix(carto): correction sur la récupération de la localisation

front/screens/aroundMe/tabAroundMeScreen.component.tsx, front/screens/epdsSurvey/epdsLightResult.component.tsx, front/utils/tracker.util.ts
Closes #648 
J'en ai profité pour ajouter un tracker sur le clic sur un POI dans la carto, comme demandé par Maxime
=> feat(epds): agrandissement bouton Être contacté + trackers

front/app.config.js, front/screens/aroundMe/tabAroundMeScreen.component.tsx
=> fix(carto): suppression loader après filtre sur iOS + incrément version

front/constants/Labels.ts, front/screens/epdsSurvey/beContacted.component.tsx, front/screens/epdsSurvey/epdsSurveyContent.component.tsx, front/type/epdsSurvey.types.ts
=> feat(epds): modification textes modale Être contacté

front/components/base/tags.component.tsx, front/components/calendar/eventCard.component.tsx, front/components/calendar/events.component.tsx, front/screens/TabCalendarScreen.tsx, front/screens/listArticles.component.tsx, front/types.tsx
=> fix: 🐛 Corrige les retours design sur les événements

front/components/menu/menu.component.tsx, front/constants/Labels.ts, front/constants/links.constants.ts
=> feat: 🎸 Ajoute "Laisser un avis" dans le menu

back/strapi/api/reponses-epds/config/schema.graphql.js, back/strapi/api/reponses-epds/services/index.js
Ajout d'un nouveau champ pour le partage des résultats EPDS à un second pro
=> feat(partage epds): Ajout d'un email pour un second pro

back/strapi/api/article/models/article.settings.js, back/strapi/api/cartographie-types/models/cartographie-types.settings.json, back/strapi/api/etape/models/etape.settings.json, back/strapi/api/evenement/models/evenement.settings.json, back/strapi/api/parentheque-documents/models/parentheque-documents.settings.json
=> feat(evenements): Ajoute les liens vers articles, documents et types de POIs

front/components/article/links.component.tsx
=> feat: 🎸 Ajoute une puce et aligne à gauche les liens article

front/constants/epdsConstants.constants.ts, front/screens/epdsSurvey/epdsLightResult.component.tsx, front/utils/epdsSurvey.util.ts
=> feat(epds): modification textes smiley + résultats

back/strapi/api/reponses-epds/services/partage-epds.js, back/strapi/package.json, back/strapi/yarn.lock
- Création du pdf identique au mail du pro
- Envoi de ce pdf en PJ au pro
=> feat(email pdf): création du pdf

front/screens/epdsSurvey/epdsLightResult.component.tsx
=> fix(epds): correction condition affichage texte d'invitation

front/constants/aroundMe.constants.ts
=> fix(carto): augmentation nombre tentatives pour récupérer la géoloc

front/components/article/articleCard.component.tsx, front/components/calendar/eventCard.component.tsx, front/components/calendar/events.component.tsx, front/components/index.ts, front/constants/Labels.ts, front/screens/TabCalendarScreen.tsx
=> feat: 🎸 ACCESSIBILITE - Ecran 7 : Calendrier

front/screens/Onboarding.tsx
=> fix(accessibilite): fix lecture iOS

front/constants/Labels.ts, front/screens/Onboarding.tsx, front/screens/customOnboardingPagination.component.tsx
=> fix(accessibilite): utilisation flatlist RN + gestion écrans

front/components/article/articleCard.component.tsx
=> fix: 🐛 Corrige le problème d'actualisation des images

front/components/calendar/eventCard.component.tsx
=> feat: 🎸 Supprime les articles liés via thematique et étape

front/App.tsx, front/app.config.js, front/constants/storageKeys.constants.ts, front/screens/TabCalendarScreen.tsx, front/utils/notification.util.ts
=> fix: 🐛 Corrige l'heure et la redirection des notifications

.github/workflows/expo-publish-develop.yml
k8s-namespace action is deprecated
=> chore(ci): use autodevops-env action

front/components/document/documentCard.component.tsx, front/screens/listParentsDocuments.component.tsx, front/utils/tracker.util.ts
=> feat(parentheque): trackers sur les télécharg. de docs

.k8s/__tests__/__snapshots__/dev.ts.snap, .k8s/__tests__/__snapshots__/preprod.ts.snap, .k8s/__tests__/__snapshots__/prod.ts.snap, .k8s/components/netpol.ts, .k8s/package.json, .k8s/yarn.lock
Add network isolation at kube level
=> fix(secu): add network policies

.github/workflows/expo-publish-develop.yml, .github/workflows/expo-publish-preprod.yml, .k8s/environments/dev/strapi.configmap.yaml, .k8s/environments/preprod/strapi.configmap.yaml
=> feat: 🎸 Ajoute une instance sentry pour isoler les logs de prod

front/components/article/filters.component.tsx, front/screens/aroundMe/aroundMeFilter.component.tsx, front/screens/aroundMe/submitNewFilter.component.tsx, front/screens/epdsSurvey/beContacted.component.tsx, front/screens/epdsSurvey/beContacted/howToBeContacted.component.tsx
=> fix: 🐛 Corrige l'affichage des modal (devices avec encoche)

CHANGELOG.md, back/strapi/api/locale/config/routes.json, back/strapi/api/locale/models/locale.settings.json, back/strapi/api/questionnaire-epds-traductions/config/routes.json, back/strapi/api/questionnaire-epds-traductions/models/questionnaire-epds-traductions.settings.json, back/strapi/api/reponses-epds/config/schema.graphql.js, back/strapi/api/reponses-epds/models/reponses-epds.settings.json, back/strapi/api/reponses-epds/services/partage-epds.js, front/screens/TabCalendarScreen.tsx
Dans le back : 
- Ajout d'une collection `Locale`
- Ajout d'une collection `Question EPDS traduction` en lien avec `Locale`
=> feat(epds): traduction EPDS

front/src/components/baseComponents/customTextInput.component.tsx, front/src/components/baseComponents/index.ts, front/src/components/search/tabAroundMeInstruction.component.tsx, front/src/constants/Labels.ts, front/src/screens/search/aroundMeMapAndList.component.tsx, front/src/screens/search/tabSearchScreen.component.tsx
=> feat(recherche): retours design

front/src/components/home/parenthequeItem.component.tsx, front/src/components/menu/menu.component.tsx, front/src/constants/index.ts, front/src/constants/steps.constants.ts, front/src/navigation/BottomTabNavigator.tsx, front/src/navigation/navigation.component.tsx
=> feat: 🎸 Ajoute le lien vers la parentheque dans le menu

front/src/components/baseComponents/loader.component.tsx, front/src/constants/steps.constants.ts, front/src/screens/calendar/tabCalendarScreen.component.tsx
=> fix: 🐛 Corrige un problème de freeze du loader (Notification)

.github/workflows/socialgouv-deactivate.yml
=> chore(ci): fix deactivate action

front/src/components/calendar/events.component.tsx, front/src/components/links/linksHandler.component.tsx, front/src/constants/storageKeys.constants.ts, front/src/screens/calendar/tabCalendarScreen.component.tsx, front/src/utils/rootNavigation.util.ts
=> fix: 🐛 Corrige la redirection via les deepLinks

front/src/screens/home/listParentsDocuments.component.tsx
=> fix: 🐛 Corrige le problème de freeze du loader (parenthèque)

front/src/screens/aroundMe/aroundMeScreen.component.tsx
Modifs apportées : 
- modif du component pour returner `null` s'il ne faut pas afficher la carte
- au retour de la fonction `setCoordinatesAndUserLocation`, on set les `coordinates` après un petit timeout sur iOS le temps que la carte soit bien à jour (voir ligne 112)
=> fix: 🐛 fix de la carto avec la geoloc sur iOS

front/src/components/epdsSurvey/epdsLoadPreviousSurvey.component.tsx, front/src/navigation/BottomTabNavigator.tsx
=> fix: 🐛 Corrige le bouton retour (historique de navigation)

front/App.tsx, front/src/constants/storageKeys.constants.ts, front/src/utils/tracker.util.test.ts, front/src/utils/tracker.util.ts
=> feat: 🎸 Modification du tracker d'ouverture de l'app

front/App.tsx, front/package.json, front/src/components/assets/baseAssets.component.ts, front/src/components/tracker/trackerHandler.component.tsx, front/src/components/tracker/trackerInit.component.tsx, front/src/constants/databaseQueries/calendarDbQueries.constants.ts, front/src/constants/databaseQueries/epdsDbQueries.constants.ts, front/src/constants/databaseQueries/homeDbQueries.constants.ts, front/src/constants/databaseQueries/searchQueries.constants.ts, front/src/constants/storageKeys.constants.ts, front/src/declarations.d.ts, front/src/services/graphQL/graphQLProvider.component.tsx, front/src/utils/storage.util.ts, front/src/utils/tracker.util.ts, front/yarn.lock
=> feat(stats): mise en place d'un userUuid pour les utilisateurs uniques sur Matomo

front/src/components/article/articlesFilter.component.tsx, front/src/components/baseComponents/closeButton.component.tsx, front/src/components/baseComponents/customButton.component.tsx, front/src/components/baseComponents/customTextInput.component.tsx, front/src/components/document/documentCard.component.tsx, front/src/components/onboarding/customOnboardingPagination.component.tsx, front/src/components/search/tabAroundMeInstruction.component.tsx, front/src/screens/onboardingAndProfile/profile.component.tsx, front/src/styles/sizes.ts
Zone tactile (min 48dp x 48dp)
- CustomButton
- CloseButton
- Profil : étape
- Modale filtre : hauteur des items
- DatePicker
- Onboarding : pagination
- Recherche : champs de recherche, icon de geoloc
Libellés de contenu
- Bouton télécharger document
=> fix: robot Google Play console sur l'accessibilité

front/src/components/article/articleCard.component.tsx
=> fix: 🐛 Corrige le problème d'image sur les articles (filtre)

front/src/components/article/articleList.component.tsx, front/src/components/article/articlesFilter.component.tsx, front/src/constants/Labels.ts, front/src/screens/articles/articleDetail.component.tsx, front/src/screens/articles/articleListScreen.component.tsx, front/src/utils/article.util.ts, front/src/utils/index.ts, front/src/utils/storage.util.ts
=> feat(article): ajout du label Article lu

front/src/components/html/li.component.tsx, front/src/components/menu/conditionsOfUse.component.tsx
=> fix: 🐛 Corrige les problèmes d'accessibilité (puces et tableau)

front/App.tsx, front/src/components/calendar/eventCard.component.tsx, front/src/screens/onboardingAndProfile/onboarding.component.tsx, front/src/utils/notification.util.ts
=> fix: 🐛 Corrige la sauvegarde des données

front/src/components/epdsSurvey/beContacted/beContactedForm.component.tsx, front/src/utils/strings.test.js, front/src/utils/strings.util.ts
Formatage pour avoir des espaces tous les 2 chiffres.
Je n'ai pas réussi à tout faire en regex, n'hésitez pas si vous avez une solution plus optimisée.
=> feat(contact): formatage du numéro de tel pour Elise

front/src/components/document/documentCard.component.tsx
- Supprimer le focus sur l'image pour chaque document
=> fix(accessibility): parenthèque

front/src/components/article/inShort.component.tsx, front/src/components/article/thematics.component.tsx, front/src/constants/Labels.ts, front/src/screens/articles/articleDetail.component.tsx
=> fix: 🐛 Rend accessible l'écran "Article"

front/src/components/epdsSurvey/epdsResultInformation/epdsResultInformation.component.tsx, front/src/screens/epdsSurvey/epdsResult.component.tsx
Focus lorsque l'on développe les ressources
=> fix(accessibilite): focus ressources

front/src/screens/onboardingAndProfile/profile.component.tsx
=> fix: 🐛 Corrige la sélection du genre sur la page profil

front/package-lock.json, front/package.json, front/src/components/article/articleCard.component.tsx, front/yarn.lock
=> fix: 🐛 Corrige le problème d'affichage des images (articles)

front/src/components/baseComponents/icomoon.component.tsx, front/src/navigation/navigation.component.tsx
=> fix: 🐛 Corrige la taille de l'icone du menu

front/src/utils/epdsSurvey.util.ts
=> fix: 🐛 getQuestionsAndAnswersFromData - check if undefined

front/src/screens/calendar/tabCalendarScreen.component.tsx
=> fix: 🐛 handle calendarSync error

back/strapi/api/reponses-epds/services/contact-confirmed.js, back/strapi/api/reponses-epds/services/contact.js
Ticket : https://github.com/SocialGouv/1000jours/issues/867
=> fix(contact): footer du mail de confirmation

front/package.json, front/yarn.lock
=> fix: 🐛 add expo-analytics-segment

front/src/utils/linking.util.ts
=> fix: 🐛 Corrige l'erreur sentry 'Unable to open URL: maps://'

front/src/components/document/documentCard.component.tsx, front/src/utils/index.ts, front/src/utils/linking/linking.util.test.ts, front/src/utils/linking/linking.util.ts
=> fix: Fix ouverture URL + ajout TUs

front/src/components/aroundMe/aroundMeFilter.component.tsx, front/src/components/aroundMe/aroundMePoiResultInformation.component.tsx, front/src/components/aroundMe/slidingUpPanelAddressesList.component.tsx, front/src/components/assets/favoritesAssets.component.tsx, front/src/components/baseComponents/titleH1.component.tsx, front/src/components/index.ts, front/src/components/search/aroundMePoiList.component.tsx
Corrige le point 7.1 de l'écran E08 (#1308) -> Absence de titres, certains titres épelé car en capitales
=> fix: fix accessibilite v2 - 7.1 E08

front/src/constants/storageKeys.constants.ts, front/src/utils/notification.util.ts
=> fix: 🐛 Corrige la programmation des notifs moodboard

front/src/constants/storageKeys.constants.ts, front/src/utils/notification.util.ts
=> fix: 🐛 Corrige la notification article de félicitations

front/src/components/aroundMe/aroundMeFilter.component.tsx, front/src/components/aroundMe/aroundMeMap.component.tsx, front/src/components/aroundMe/fetchPois.component.tsx, front/src/components/baseComponents/chip.component.tsx, front/src/components/baseComponents/customButton.component.tsx, front/src/components/calendar/eventCard.component.tsx, front/src/components/search/aroundMePoiList.component.tsx, front/src/constants/Labels.ts, front/src/hooks/index.ts, front/src/hooks/useSavedCartographyFilters.ts, front/src/type/aroundMe.types.ts, front/src/utils/aroundMe/aroundMeFilter.util.test.ts, front/src/utils/aroundMe/aroundMeFilter.util.ts, front/src/utils/index.ts, front/src/utils/search.util.ts
Closes #1334 
Closes partially 5.1 - E08 #1308
=> feat: modale filtres cartographie bouton valider + refacto

front/src/utils/notification.util.test.ts, front/src/utils/notification.util.ts
=> fix: 🐛 Corrige la date de déclenchement des notifs article

front/src/components/article/articleCard.component.tsx, front/src/components/article/articleList.component.tsx, front/src/components/article/articleListHeader.component.tsx, front/src/components/baseComponents/favoriteButton.component.tsx, front/src/components/baseComponents/usefulQuestion.component.tsx, front/src/components/menu/menu.component.tsx, front/src/constants/Labels.ts, front/src/constants/databaseQueries/homeDbQueries.constants.ts, front/src/navigation/BottomTabNavigator.tsx, front/src/screens/articles/articleDetail.component.tsx, front/src/screens/articles/articleFavorites.component.tsx, front/src/screens/articles/articleListScreen.component.tsx, front/src/screens/index.ts, front/src/types.tsx, front/src/utils/tracker.util.ts
=> feat: 🎸 Ajoute l'écran des favoris

front/src/screens/search/tabSearchScreen.component.tsx
J'ai sécurisé l'erreur pour ne pas faire crasher l'app.
=> fix(article): articles undefined

front/src/components/baseComponents/favoriteButton.component.tsx
=> feat: ajout tracking favoris

front/src/components/baseComponents/favoriteButton.component.tsx, front/src/constants/Labels.ts
=> fix: 🐛 Corrige l'accessibilité des favoris

front/src/components/article/articleList.component.tsx, front/src/components/article/articleListHeader.component.tsx, front/src/screens/articles/articleFavorites.component.tsx
=> fix: 🐛 Corrige l'affichage du message 'empty' (favoris)

front/src/components/article/articleCard.component.tsx, front/src/components/article/articleList.component.tsx, front/src/components/baseComponents/favoriteButton.component.tsx, front/src/screens/articles/articleFavorites.component.tsx, front/src/screens/articles/articleListScreen.component.tsx
=> fix: 🐛 Mise à jour des écrans après la mise en favoris

front/src/components/moodboard/moodsCalendar.component.tsx, front/src/constants/Labels.ts, front/src/screens/moodboard/moodboard.component.tsx
=> feat: 🎸 Améliore le suivi d'humeur

back/strapi/api/config/config/routes.json, back/strapi/api/config/models/config.settings.json
=> feat: 🎸 Ajoute une nouvelle collection 'Config' (Strapi)

front/src/assets/images/checkbox_checked.svg, front/src/assets/images/checkbox_unchecked.svg, front/src/components/article/articleListHeader.component.tsx, front/src/components/article/articlesFilter.component.tsx, front/src/components/article/articlesFilterFavoritesRow.component.tsx, front/src/components/assets/baseAssets.component.ts, front/src/components/baseComponents/customDivider.component.tsx, front/src/components/index.ts, front/src/constants/Labels.ts, front/src/hooks/index.ts, front/src/hooks/useFavoriteArticlesIds.ts, front/src/utils/articles/articleFilter.util.test.ts, front/src/utils/articles/articleFilter.util.ts
=> feat(articles): ajout filtre favoris

front/src/components/moodboard/moodsCalendar.component.tsx, front/src/screens/moodboard/moodboard.component.tsx, front/src/types.tsx, front/src/utils/moodboard/moodboard.util.ts
=> fix: 🐛 Corrige un problème de refresh sur le moodboard

front/src/components/baseComponents/customDivider.component.tsx, front/src/components/index.ts, front/src/components/menu/infosDev.component.tsx, front/src/components/notification/notificationModal.component.tsx, front/src/components/notification/notificationToggle.component.tsx, front/src/constants/Labels.ts, front/src/constants/storageKeys.constants.ts, front/src/screens/notificationsCenter/notificationsCenter.component.tsx, front/src/utils/app.util.ts, front/src/utils/index.ts, front/src/utils/notifications/notification.util.test.ts, front/src/utils/notifications/notification.util.ts, front/src/utils/notifications/notificationToggle.util.test.ts, front/src/utils/notifications/notificationToggle.util.ts
=> feat(notifications): ajout toggle suivi humeur

front/src/components/notification/notificationToggle.component.tsx
=> feat(notif): ajout des stats

front/src/utils/notifications/notification.util.test.ts, front/src/utils/notifications/notification.util.ts
=> fix: 🐛 Corrige une erreur sentry 'b.includes is not a function'

front/src/components/menu/menu.component.tsx
=> fix: 🐛 Désactive l'accès au centre de notifications

front/src/utils/notifications/notificationToggle.util.test.ts, front/src/utils/notifications/notificationToggle.util.ts
=> fix: 🐛 Les 'Toogles' sont activés par défaut (notifs)

front/src/components/notification/notificationToggle.component.tsx, front/src/constants/Labels.ts, front/src/constants/storageKeys.constants.ts, front/src/hooks/index.ts, front/src/hooks/useEvents.ts, front/src/screens/calendar/tabCalendarScreen.component.tsx, front/src/screens/notificationsCenter/notificationsCenter.component.tsx, front/src/utils/events/event.util.ts, front/src/utils/events/events.util.test.ts, front/src/utils/index.ts, front/src/utils/notifications/notification.util.ts, front/src/utils/notifications/notificationToggle.util.test.ts, front/src/utils/notifications/notificationToggle.util.ts
J'arrive au bout, mais j'ai un doute sur une valeur ...
Lorsque j'active les notifs `events`, le BO m'en renvoie 81, mais lorsque que je fais un `getAllNotificationsByType(NotificationType.event)` pour vérifier qu'elle ont été réactivées, j'en ai 110
=> feat(notif): paramétrer les notifs d'événement

front/src/components/article/articlesFilter.component.tsx, front/src/components/baseComponents/blueCheckbox.component.tsx, front/src/components/baseComponents/greenRadioButton.component.tsx, front/src/components/baseComponents/index.ts, front/src/components/epdsSurvey/epdsGenderEntry.component.tsx, front/src/components/epdsSurvey/epdsQuestion.component.tsx, front/src/components/notification/notificationsEssentialEvents.component.tsx
=> refacto(checkbox): mutualisation checkbox

back/strapi/api/video/models/video.js, back/strapi/api/video/services/index.js
=> fix: 🐛 Corrige l'url des miniatures des videos

front/src/components/document/documentCard.component.tsx, front/src/components/index.ts, front/src/components/menu/menu.component.tsx, front/src/components/parentheque/tabParenthequeDocuments.component.tsx, front/src/components/parentheque/tabParenthequeVideos.component.tsx, front/src/constants/Labels.ts, front/src/screens/home/parentheque.component.tsx
Closes #1478 
https://user-images.githubusercontent.com/55133704/197959156-d300aa76-ead5-47ee-bb93-5b9aaca1b5d6.mp4
=> feat(videotheque): ajout tab videos dans la parentheque

front/src/screens/home/tabHomeScreen.component.tsx, front/src/screens/onboardingAndProfile/profile.component.tsx, front/src/utils/notifications/notification.util.ts, front/src/utils/step/step.util.test.ts, front/src/utils/step/step.util.ts
=> refacto(step): ajout et refacto TUs StepUtils

front/src/components/app/checkAppVersion.component.tsx
=> fix: 🐛 Corrige une erreur Sentry (undefined is not an object)

front/src/components/baseComponents/shareButton.component.tsx, front/src/components/menu/menu.component.tsx, front/src/components/storage/storeCurrentStepArticleIds.component.tsx, front/src/constants/Labels.ts, front/src/constants/links.constants.ts, front/src/constants/platform.constants.ts, front/src/utils/index.ts, front/src/utils/share/share.util.test.ts, front/src/utils/share/share.util.ts, front/src/utils/tracking/tracker.util.ts
=> feat: 🎸 Ajoute la recommandation de l'app dans le menu

front/app.config.js, front/package.json, front/src/components/menu/menu.component.tsx, front/src/components/notification/notificationModal.component.tsx, front/src/constants/links.constants.ts, front/src/utils/linking/linking.util.ts, front/yarn.lock
Closes #1523 
POC rapide sur la lib expo-store-review pour faire des reviews in-app
=> feat(in-app review): POC in app review

front/src/components/article/textHtml.component.tsx, front/src/screens/articles/articleDetail.component.tsx, front/src/utils/html/html.util.test.ts, front/src/utils/html/html.util.ts, front/src/utils/index.ts
=> fix: 🐛 Corrige l'affichage et l'autoplay sur les vidéos

front/App.tsx, front/src/components/menu/menu.component.tsx, front/src/components/notification/notificationModal.component.tsx, front/src/constants/Labels.ts, front/src/constants/storageKeys.constants.ts, front/src/utils/app/app.util.test.ts, front/src/utils/app/app.util.ts, front/src/utils/index.ts, front/src/utils/notifications/inappreview/inAppReview.util.test.ts, front/src/utils/notifications/inappreview/inAppReview.util.ts, front/src/utils/notifications/notification.util.ts
=> feat(in-app review): popup in app review

front/App.tsx, front/src/utils/html/html.util.ts, front/src/utils/notifications/inappreview/inAppReview.util.ts, front/src/utils/notifications/notification.util.ts
=> fix: 🐛 Corrige la notification 'InAppReview'

front/src/constants/databaseQueries/searchQueries.constants.ts
=> feat: 🎸 Affiche uniquement les filtres POIs non vides

back/strapi/api/config/models/config.js, back/strapi/api/config/models/config.settings.json, back/strapi/api/config/services/index.js, front/src/components/app/checkAppVersion.component.tsx, front/src/components/app/newFeatures.component.tsx, front/src/components/menu/menu.component.tsx, front/src/constants/Labels.ts, front/src/constants/databaseQueries/configDbQueries.constants.ts, front/src/constants/storageKeys.constants.ts, front/src/navigation/navigation.component.tsx, front/src/types.tsx, front/src/utils/app/app.util.test.ts, front/src/utils/app/app.util.ts, front/src/utils/html/html.util.ts, front/src/utils/strings/strings.util.ts
=> feat: 🎸 Ajoute une popup pour afficher les nouveautés

front/package.json, front/yarn.lock
=> fix: 🐛 Corrige l'affichage en dark mode sur Android (EAS build)

front/src/components/survey/surveyQuestionsList.component.tsx
=> fix: 🐛 Corrige le carousel des questions TND (>11 questions)

front/src/components/app/checkAppVersion.component.tsx, front/src/components/menu/infosDev.component.tsx, front/src/components/notification/notificationModal.component.tsx, front/src/constants/Labels.ts, front/src/screens/onboardingAndProfile/profile.component.tsx, front/src/utils/app/app.util.test.ts, front/src/utils/app/app.util.ts, front/src/utils/index.ts, front/src/utils/notifications/notification.util.ts, front/src/utils/notifications/tnd/tndNotification.util.test.ts, front/src/utils/notifications/tnd/tndNotification.util.ts
=> feat: 🎸 Ajoute les notifications TND pour passer le test

back/strapi/api/article/services/index.js
=> fix: 🐛 Corrige la recherche article

.github/workflows/preproduction.yaml, .github/workflows/production.yaml, .github/workflows/review-auto.yaml, .github/workflows/review.yaml, .kontinuous/config.yaml, .kontinuous/env/dev/values.yaml, .kontinuous/env/preprod/values.yaml, .kontinuous/env/prod/values.yaml, .kontinuous/values.yaml, back/strapi/Dockerfile, back/strapi/config/database.js
- utilisation de [CNPG](https://cloudnative-pg.io/) en  dev/preprod/prod
- use harbor for docker registry
- le restore fonctionne toujours avec les CSI azure pour l'instant
=> fix: add CNPG prod cluster

front/src/constants/Labels.ts, front/src/screens/surveys/tabSurveysScreen.component.tsx
=> feat(recosante): add recosante widget on evaluation page

.kontinuous/env/prod/values.yaml
=> fix: 1000jours strapi resources

.kontinuous/env/prod/values.yaml
=> fix:1000j-resources
